routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'DashboardController')->name('dashboard');
Route::resource('orders', 'OrderController')->only('index');
Route::resource('products', 'ProductController')->only('index', 'create', 'edit', 'destroy');

Route::resource('photos', 'PhotoController')->only('store');
Route::get('settings', 'SettingController')->name('settings');
Route::get('texts', 'TextController')->name('texts');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome');

Route::get('products', 'ProductController@index')->name('products.index');
Route::get('products/{product}', 'ProductController@show')->name('products.show');
Route::get('pages/{page}', 'PageController@show')->name('pages.show');

Route::get('auth', 'AuthController@create')->name('auth.create');

app/Http/Livewire/Admin/Contact.php
<?php

namespace App\Http\Livewire\Admin;

use App\Mail;
use App\User;
use Livewire\Component;

class Contact extends Component
{
    public $title;
    public $description;
    public $success = false;
    public $email;

    public function mount()
    {
        $this->email = User::whereIsAdmin(true)->value('email');
    }

    public function send()
    {
        $validated = $this->validate([
            'title' => 'required|string|max:40',
            'description' => 'required|string|max:65000',
        ]);

        Mail::create($validated + ['from' => $this->email]);

        $this->success = true;
    }
}

app/Http/Livewire/Admin/SaveProduct.php
<?php

namespace App\Http\Livewire\Admin;

use Cache;
use App\Product;
use Livewire\Component;
use Illuminate\Support\Arr;

class SaveProduct extends Component
{
    public $productId;
    public $photo;
    public $title;
    public $price;
    public $description;
    public $isFeatured;

    public function mount(?Product $product = null)
    {
        $this->fill([
            'isFeatured' => $product->is_featured,
            'productId' => $product->id,
        ] + Arr::only($product->getAttributes(), [
            'productId', 'photo', 'title', 'price', 'description'
        ]));
    }

    public function save()
    {
        $validated = $this->validate([
            'photo' => 'required|uploaded',
            'title' => 'required|string|max:40',
            'price' => 'required|numeric|between:1,999999',
            'description' => 'required|string',
            'isFeatured' => 'nullable|bool',
        ]);

        $validated = [
            'is_featured' => $validated['isFeatured'] ?? false
        ] + Arr::except($validated, 'isFeatured');

        $this->productId ? Product::where('id', $this->productId)->update($validated) : Product::create($validated);

        Cache::forget('featured-products');

        return redirect()->route('admin.products.index');
    }
}

app/Http/Livewire/Admin/SaveSettings.php
<?php

namespace App\Http\Livewire\Admin;

use DB;
use Cache;
use Livewire\Component;
use Illuminate\Support\Arr;

class SaveSettings extends Component
{
    public $name;
    public $color;

    public function mount()
    {
        $this->fill(Arr::only(settings()->getAttributes(), ['name', 'color']));
    }

    public function save()
    {
        $validated = $this->validate([
            'name' => 'required|string|max:40',
            'color' => 'required|string|in:red,green,orange,blue,purple,pink',
        ]);

        DB::table('settings')->update($validated);

        Cache::forget('settings');

        return redirect()->route('admin.settings');
    }
}

app/Http/Livewire/Admin/SaveTexts.php
<?php

namespace App\Http\Livewire\Admin;

use DB;
use Cache;
use Livewire\Component;
use Illuminate\Support\Arr;

class SaveTexts extends Component
{
    public $products_text;
    public $landing_hero_title;
    public $landing_hero_description;
    public $landing_hero_c2a;
    public $landing_quality_title;
    public $landing_quality_description;
    public $landing_delivery_title;
    public $landing_delivery_description;
    public $landing_payment_title;
    public $landing_payment_description;
    public $page_delivery;
    public $page_personal_data;
    public $page_terms;

    public function mount()
    {
        $this->fill(Arr::only(settings()->getAttributes(), [
            'products_text',
            'landing_hero_title',
            'landing_hero_description',
            'landing_hero_c2a',
            'landing_quality_title',
            'landing_quality_description',
            'landing_delivery_title',
            'landing_delivery_description',
            'landing_payment_title',
            'landing_payment_description',
            'page_delivery',
            'page_personal_data',
            'page_terms',
        ]));
    }

    public function save()
    {
        $validated = $this->validate([
            'products_text' => 'required|string|max:40',
            'landing_hero_title' => 'required|string|max:40',
            'landing_hero_description' => 'required|string|max:80',
            'landing_hero_c2a' => 'required|string|max:40',
            'landing_quality_title' => 'required|string|max:40',
            'landing_quality_description' => 'required|string|max:255',
            'landing_delivery_title' => 'required|string|max:40',
            'landing_delivery_description' => 'required|string|max:255',
            'landing_payment_title' => 'required|string|max:40',
            'landing_payment_description' => 'required|string|max:255',
            'page_delivery' => 'required|string|max:65000',
            'page_personal_data' => 'required|string|max:65000',
            'page_terms' => 'required|string|max:65000',
        ]);

        DB::table('settings')->update($validated);

        Cache::forget('settings');

        return redirect()->route('admin.texts');
    }
}

app/Http/Livewire/Admin/ShowOrders.php
<?php

namespace App\Http\Livewire\Admin;

use App\Order;
use Livewire\Component;

class ShowOrders extends Component
{
    public $orders;

    public function mount()
    {
        $this->refreshOrders();
    }

    public function render()
    {
        return view('livewire.admin.show-orders');
    }

    public function refreshOrders()
    {
        $this->orders = Order::latest()->with('product')->get();
    }

    public function changeStatus(int $id, string $status)
    {
        Order::where('id', $id)->update(compact('status'));

        $this->refreshOrders();
    }
}

app/Http/Livewire/Admin/ShowProducts.php
<?php

namespace App\Http\Livewire\Admin;

use Cache;
use App\Order;
use App\Product;
use Livewire\Component;

class ShowProducts extends Component
{
    public $products;
    public $hasDeletionFailed = false;

    public function mount()
    {
        $this->products = Product::latest()->get();
    }
    
    public function delete(int $id)
    {
        if (Order::whereProductId($id)->exists()) {
            return $this->hasDeletionFailed = true;
        }

        $product = Product::find($id);

        if ($product->is_featured) {
            Cache::forget('featured-products');
        }

        $product->delete();

        $this->products = Product::latest()->get();
    }
}

app/Http/Livewire/Auth.php
<?php

namespace App\Http\Livewire;

use Auth as AuthFacade;
use Livewire\Component;

class Auth extends Component
{
    public $email;
    public $password;
    public $hasErrors = false;

    public function render()
    {
        return view('livewire.auth');
    }

    public function auth()
    {
        $this->reset('hasErrors');

        $credentials = [
            'email' => $this->email,
            'password' => $this->password,
            'is_admin' => true,
        ];

        if (AuthFacade::attempt($credentials, $remember = true)) {
            return redirect()->intended('dashboard');
        }

        $this->hasErrors = true;
    }
}

app/Http/Livewire/Logout.php
<?php

namespace App\Http\Livewire;

use Auth;
use Livewire\Component;

class Logout extends Component
{
    public function render()
    {
        return view('livewire.logout');
    }

    public function logout()
    {
        Auth::logout();

        return redirect('/');
    }
}

app/Http/Livewire/ShowProduct.php
<?php

namespace App\Http\Livewire;

use Auth;
use Livewire\Component;
use Illuminate\Support\Str;
use Illuminate\Support\Arr;
use App\ { Product, Order, User};

class ShowProduct extends Component
{
    public $product;
    public $phone;
    public $address;
    public $additions;
    public $success = false;
    public $user;

    public function mount(Product $product)
    {
        $this->product = $product;
        $this->user = Auth::user();

        if ($this->user) {
            $this->fill(Arr::only($this->user->getAttributes(), ['phone', 'address', 'additions']));
        }
    }

    public function order()
    {
        $validated = $this->validate([
            'phone' => 'required|string|min:10|max:20',
            'address' => 'required|string|min:10|max:255',
            'additions' => 'nullable|string|max:255',
        ]);

        Order::create($validated + [
            'product_id' => $this->product->id,
            'status' => 'Обработва се',
        ]);

        if ($this->user) {
            $this->user->update($validated);
        } else {
            $this->user = User::create($validated + [
                'email' => Str::random().time().'@fifi.fifi',
                'password' => Str::random(),
                'is_admin' => false,
            ]);
        }

        Auth::login($this->user, $remember = true);

        $this->success = true;
    }
}

app/Http/Livewire/ShowProducts.php
<?php

namespace App\Http\Livewire;

use App\Product;
use Livewire\Component;
use Livewire\WithPagination;

class ShowProducts extends Component
{
    use WithPagination;

    public function render()
    {
        return view('livewire.show-products', [
            'products' => Product::latest()->paginate(12),
        ]);
    }
}

resources/views/livewire/admin/contact.blade.php
<div class="mt-6">
    @if ($success)
        <div class="bg-blue-200 text-blue-700 rounded p-4">
            Получихме Вашето запитване, ще Ви отговорим при първа възможност на посочения от Вас мейл: {{ $email }}
        </div>
    @else
        <form wire:submit.prevent="send">
            <div>
                <label for="title">Тема</label>
                <input
                    wire:model.lazy="title"
                    id="title"
                    class="form-input block w-full sm:text-sm sm:leading-5"
                    placeholder="пример: Как да сменя цвета на сайта?"
                />
                @error('title') <div class="text-red-600">{{ $message }}</div> @enderror
            </div>

            <div class="mt-6">
                <label for="description">Описание</label>
                <textarea
                    wire:model.lazy="description"
                    id="description"
                    class="form-input block w-full sm:text-sm sm:leading-5"
                    placeholder="пример: Не мога да се ориентирам къде да вляза, за да..."
                    rows="6"
                ></textarea>
                @error('description') <div class="text-red-600">{{ $message }}</div> @enderror
            </div>

            <div class="mt-6">
                <x:button tag="button">
                    Изпрати
                </x:button>
            </div>
        </form>
    @endif
</div>

resources/views/livewire/admin/save-product.blade.php
<form wire:submit.prevent="save">
    @if ($productId)
        <img src="{{ Storage::url($photo) }}" class="w-64" />
    @endif

    <div class="mt-6 w-full lg:w-1/3">
        <x:file-input wire:model="photo" />
        @error('photo') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6">
        <label for="title">Име</label>
        <input
            wire:model.lazy="title"
            id="title"
            class="form-input block w-full md:w-1/3 sm:text-sm sm:leading-5"
            placeholder="Име"
        />
        @error('title') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6">
        <label for="price">Цена</label>
        <input
            wire:model.lazy="price"
            id="price"
            class="form-input block w-full md:w-1/3 sm:text-sm sm:leading-5"
            placeholder="Цена"
        />
        @error('price') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6">
        <label for="description">Описание</label>
        <textarea
            wire:model.lazy="description"
            id="description"
            class="form-input block w-full md:w-2/3 sm:text-sm sm:leading-5"
            placeholder="Описание"
            rows="6"
        ></textarea>
        @error('description') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6">
        <input
            wire:model.lazy="isFeatured"
            type="checkbox"
            id="isFeatured"
        />

        <label for="isFeatured">На заглавна страница?</label>
        @error('isFeatured') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6">
        <x:button tag="button">
            Запази
        </x:button>
    </div>
</form>

resources/views/livewire/admin/save-settings.blade.php
<form wire:submit.prevent="save">
    <div><!-- Name -->
        <label for="name">Име</label>
        <input
            wire:model.lazy="name"
            id="name"
            class="form-input block w-full md:w-1/3 sm:text-sm sm:leading-5"
            placeholder="Име"
        />
        @error('name') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6"><!-- Color -->
        <label for="name">Цвят</label>

        <div class="flex items-center mt-3 md:text-3xl">
            <input
                wire:model="color"
                type="radio"
                id="color-red"
                value="red"
                class="hidden"
            />
            <label
                for="color-red"
                class="block w-8 h-8 md:w-12 md:h-12 bg-red-600 rounded-full shadow {{ $color == 'red' ? 'transform scale-125 shadow-inner border-4 border-red-900 shadow-xl' : 'border border-red-500' }}"
            ></label>
            
            <input
                wire:model="color"
                type="radio"
                id="color-green"
                value="green"
                class="hidden"
            />
            <label
                for="color-green"
                class="ml-3 block w-8 h-8 md:w-12 md:h-12 bg-green-600 rounded-full shadow {{ $color == 'green' ? 'transform scale-125 shadow-inner border-4 border-green-900 shadow-xl' : 'border border-green-500' }}"
            ></label>
            
            <input
                wire:model="color"
                type="radio"
                id="color-blue"
                value="blue"
                class="hidden"
            />
            <label
                for="color-blue"
                class="ml-3 block w-8 h-8 md:w-12 md:h-12 bg-blue-600 rounded-full shadow {{ $color == 'blue' ? 'transform scale-125 shadow-inner border-4 border-blue-900 shadow-xl' : 'border border-blue-500' }}"
            ></label>
            
            <input
                wire:model="color"
                type="radio"
                id="color-orange"
                value="orange"
                class="hidden"
            />
            <label
                for="color-orange"
                class="ml-3 block w-8 h-8 md:w-12 md:h-12 bg-orange-600 rounded-full shadow {{ $color == 'orange' ? 'transform scale-125 shadow-inner border-4 border-orange-900 shadow-xl' : 'border border-orange-500' }}"
            ></label>
            
            <input
                wire:model="color"
                type="radio"
                id="color-purple"
                value="purple"
                class="hidden"
            />
            <label
                for="color-purple"
                class="ml-3 block w-8 h-8 md:w-12 md:h-12 bg-purple-600 rounded-full shadow {{ $color == 'purple' ? 'transform scale-125 shadow-inner border-4 border-purple-900 shadow-xl' : 'border border-purple-500' }}"
            ></label>
            
            <input
                wire:model="color"
                type="radio"
                id="color-pink"
                value="pink"
                class="hidden"
            />
            <label
                for="color-pink"
                class="ml-3 block w-8 h-8 md:w-12 md:h-12 bg-pink-600 rounded-full shadow {{ $color == 'pink' ? 'transform scale-125 shadow-inner border-4 border-pink-900 shadow-xl' : 'border border-pink-500' }}"
            ></label>
        </div>
    
        @error('color')
            <div class="mt-1 text-red-400 text-sm">{{ $message }}</div>
        @enderror
    </div>

    <div class="mt-10">
        <x:button tag="button">
            Запази
        </x:button>
    </div>
</form>

resources/views/livewire/admin/save-texts.blade.php
<form wire:submit.prevent="save">
    <div><!-- Products Text -->
        <label for="products_text">Какви са Вашите продукти? Например: Дрехи</label>
        <input
            wire:model.lazy="products_text"
            id="products_text"
            class="form-input block w-full md:w-1/5 sm:text-sm sm:leading-5"
        />
        @error('products_text') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6"><!-- Landing Page Title -->
        <label for="landing_hero_title">Заглавие в началната страница</label>
        <input
            wire:model.lazy="landing_hero_title"
            id="landing_hero_title"
            class="form-input block w-full md:w-1/3 sm:text-sm sm:leading-5"
        />
        @error('landing_hero_title') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6"><!-- Landing Page Description -->
        <label for="landing_hero_description">Кратко изречение в началната страница</label>
        <input
            wire:model.lazy="landing_hero_description"
            id="landing_hero_description"
            class="form-input block w-full md:w-2/3 sm:text-sm sm:leading-5"
        />
        @error('landing_hero_description') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6"><!-- Landing Page C2A -->
        <label for="landing_hero_c2a">Бутон в началната страница</label>
        <input
            wire:model.lazy="landing_hero_c2a"
            id="landing_hero_c2a"
            class="form-input block w-full md:w-1/3 sm:text-sm sm:leading-5"
        />
        @error('landing_hero_c2a') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6"><!-- Landing Page Quality Title -->
        <label for="landing_quality_title">Представяне #1 Заглавие</label>
        <input
            wire:model.lazy="landing_quality_title"
            id="landing_quality_title"
            class="form-input block w-full md:w-1/5 sm:text-sm sm:leading-5"
        />
        @error('landing_quality_title') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6"><!-- Landing Page Quality Description -->
        <label for="landing_quality_description">Представяне #1 Описание</label>
        <input
            wire:model.lazy="landing_quality_description"
            id="landing_quality_description"
            class="form-input block w-full sm:text-sm sm:leading-5"
        />
        @error('landing_quality_description') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6"><!-- Landing Page Delivery Title -->
        <label for="landing_delivery_title">Представяне #2 Заглавие</label>
        <input
            wire:model.lazy="landing_delivery_title"
            id="landing_delivery_title"
            class="form-input block w-full md:w-1/5 sm:text-sm sm:leading-5"
        />
        @error('landing_delivery_title') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6"><!-- Landing Page Delivery Description -->
        <label for="landing_delivery_description">Представяне #2 Описание</label>
        <input
            wire:model.lazy="landing_delivery_description"
            id="landing_delivery_description"
            class="form-input block w-full sm:text-sm sm:leading-5"
        />
        @error('landing_delivery_description') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6"><!-- Landing Page Payment Title -->
        <label for="landing_payment_title">Представяне #3 Заглавие</label>
        <input
            wire:model.lazy="landing_payment_title"
            id="landing_payment_title"
            class="form-input block w-full md:w-1/5 sm:text-sm sm:leading-5"
        />
        @error('landing_payment_title') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6"><!-- Landing Page payment Description -->
        <label for="landing_payment_description">Представяне #3 Описание</label>
        <input
            wire:model.lazy="landing_payment_description"
            id="landing_payment_description"
            class="form-input block w-full sm:text-sm sm:leading-5"
        />
        @error('landing_payment_description') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6"><!-- Page Delivery -->
        <label for="page_delivery">Страница "Поръчка и доставка"</label>
        <textarea
            wire:model.lazy="page_delivery"
            id="page_delivery"
            class="form-input block w-full md:w-2/3 sm:text-sm sm:leading-5"
            rows="10"
        ></textarea>
        @error('page_delivery') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6"><!-- Page Personal -->
        <label for="page_personal_data">Страница "Лични данни"</label>
        <textarea
            wire:model.lazy="page_personal_data"
            id="page_personal_data"
            class="form-input block w-full md:w-2/3 sm:text-sm sm:leading-5"
            rows="10"
        ></textarea>
        @error('page_personal_data') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6"><!-- Page Terms -->
        <label for="page_terms">Страница "Общи условия"</label>
        <textarea
            wire:model.lazy="page_terms"
            id="page_terms"
            class="form-input block w-full md:w-2/3 sm:text-sm sm:leading-5"
            rows="10"
        ></textarea>
        @error('page_terms') <div class="text-red-600">{{ $message }}</div> @enderror
    </div>

    <div class="mt-6">
        <x:button tag="button">
            Запази
        </x:button>
    </div>
</form>

resources/views/livewire/admin/show-products.blade.php
<div>
    @if ($hasDeletionFailed)
        <div class="mb-6 bg-red-500 text-red-100 rounded p-6">
            Изтриването не е възможно, тъй като съществуват поръчки с този продукт
        </div>
    @endif

    @if ($products->count() == 0)
        <div class="mt-10 lg:w-1/3">
            <h1 class="font-bold text-xl">
                Няма добавени продукти
            </h1>

            <div class="mt-10">
                @include('common.illustrations.empty')
            </div>

            <x-button
                tag="a"
                :href="route('admin.products.create')"
                class="mt-10 shadow"
            >
                Добавете Първия Продукт
            </x-button>
        </div>
    @else
        <x-button
            tag="a"
            :href="route('admin.products.create')"
            class="shadow"
        >
            Нов Продукт
        </x-button>

        <div class="flex flex-col mt-6">
            <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
                <div class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200">
                    <table class="min-w-full">
                    <thead>
                        <tr>
                            <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                                Продукт
                            </th>
                            <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                                Описание
                            </th>
                            <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                                На заглавна страница?
                            </th>
                            <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                                Създадена
                            </th>
                            <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                                Опции
                            </th>
                        </tr>
                    </thead>
                    <tbody class="bg-white">
                        @foreach($products as $product)
                            <tr>
                                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                                    <div class="flex items-center">
                                        <img
                                            src="{{ Storage::url($product->photo) }}"
                                            class="w-8 h-8 object-cover rounded-full"
                                        />
                                        <div class="ml-6">
                                            <div class="text-sm leading-5 font-medium text-gray-900">
                                                {{ $product->title }}
                                            </div>
                                            <div class="text-xl leading-5 font-medium text-gray-900">
                                                {{ $product->price }}<span class="text-sm">лв</span>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                                    <div class="text-sm leading-5 text-gray-900 truncate w-64">
                                        {{ $product->description }}
                                    </div>
                                </td>
                                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full @if($product->is_featured) bg-green-100 text-green-800 @else bg-red-100 text-red-800 @endif">
                                        @if($product->is_featured) Да @else Не @endif
                                    </span>
                                </td>
                                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-500">
                                    {{ $product->created_at->diffForHumans() }}
                                </td>
                                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-500">
                                    <div x-data="{ open: false }" class="relative">
                                        <a
                                            x-show="! open"
                                            @click.prevent="open = true"
                                            href="#"
                                            class="text-3xl tracking-widest font-bold"
                                        >...</a>
                                
                                        <ul
                                            x-show="open"
                                            @click.away="open = false"
                                            class="z-10 absolute bottom-0 right-0 rounded shadow-xl bg-gray-100 py-4 px-6"
                                        >
                                            <li class="pb-4">
                                                <a href="{{ route('admin.products.edit', $product) }}">
                                                    Редактирай
                                                </a>
                                            </li>
                                            <li>
                                                <a
                                                    wire:click.prevent="delete({{ $product->id }})"
                                                    @click.prevent="open = false"
                                                    href="#"
                                                >
                                                    Изтрий
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                    </table>
                </div>
            </div>
        </div>
    @endif
</div>