routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'DashboardController')->name('dashboard');
Route::resource('orders', 'OrderController')->only('index');
Route::resource('products', 'ProductController')->only('index', 'create', 'edit', 'destroy');

Route::resource('photos', 'PhotoController')->only('store');
Route::get('settings', 'SettingController')->name('settings');
Route::get('texts', 'TextController')->name('texts');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome');

Route::get('products', 'ProductController@index')->name('products.index');
Route::get('products/{product}', 'ProductController@show')->name('products.show');
Route::get('pages/{page}', 'PageController@show')->name('pages.show');

Route::get('auth', 'AuthController@create')->name('auth.create');

app/Http/Livewire/Admin/Contact.php
<?php

namespace App\Http\Livewire\Admin;

use App\Mail;
use App\User;
use Livewire\Component;

class Contact extends Component
{
    public $title;
    public $description;
    public $success = false;
    public $email;

    public function mount()
    {
        $this->email = User::whereIsAdmin(true)->value('email');
    }

    public function send()
    {
        $validated = $this->validate([
            'title' => 'required|string|max:40',
            'description' => 'required|string|max:65000',
        ]);

        Mail::create($validated + ['from' => $this->email]);

        $this->success = true;
    }
}

app/Http/Livewire/Admin/SaveSettings.php
<?php

namespace App\Http\Livewire\Admin;

use DB;
use Cache;
use Livewire\Component;
use Illuminate\Support\Arr;

class SaveSettings extends Component
{
    public $name;
    public $color;

    public function mount()
    {
        $this->fill(Arr::only(settings()->getAttributes(), ['name', 'color']));
    }

    public function save()
    {
        $validated = $this->validate([
            'name' => 'required|string|max:40',
            'color' => 'required|string|in:red,green,orange,blue,purple,pink',
        ]);

        DB::table('settings')->update($validated);

        Cache::forget('settings');

        return redirect()->route('admin.settings');
    }
}

app/Http/Livewire/Admin/SaveTexts.php
<?php

namespace App\Http\Livewire\Admin;

use DB;
use Cache;
use Livewire\Component;
use Illuminate\Support\Arr;

class SaveTexts extends Component
{
    public $products_text;
    public $landing_hero_title;
    public $landing_hero_description;
    public $landing_hero_c2a;
    public $landing_quality_title;
    public $landing_quality_description;
    public $landing_delivery_title;
    public $landing_delivery_description;
    public $landing_payment_title;
    public $landing_payment_description;
    public $page_delivery;
    public $page_personal_data;
    public $page_terms;

    public function mount()
    {
        $this->fill(Arr::only(settings()->getAttributes(), [
            'products_text',
            'landing_hero_title',
            'landing_hero_description',
            'landing_hero_c2a',
            'landing_quality_title',
            'landing_quality_description',
            'landing_delivery_title',
            'landing_delivery_description',
            'landing_payment_title',
            'landing_payment_description',
            'page_delivery',
            'page_personal_data',
            'page_terms',
        ]));
    }

    public function save()
    {
        $validated = $this->validate([
            'products_text' => 'required|string|max:40',
            'landing_hero_title' => 'required|string|max:40',
            'landing_hero_description' => 'required|string|max:80',
            'landing_hero_c2a' => 'required|string|max:40',
            'landing_quality_title' => 'required|string|max:40',
            'landing_quality_description' => 'required|string|max:255',
            'landing_delivery_title' => 'required|string|max:40',
            'landing_delivery_description' => 'required|string|max:255',
            'landing_payment_title' => 'required|string|max:40',
            'landing_payment_description' => 'required|string|max:255',
            'page_delivery' => 'required|string|max:65000',
            'page_personal_data' => 'required|string|max:65000',
            'page_terms' => 'required|string|max:65000',
        ]);

        DB::table('settings')->update($validated);

        Cache::forget('settings');

        return redirect()->route('admin.texts');
    }
}

resources/views/admin/dashboard.blade.php
@extends('layouts.admin', ['title' => 'Табло'])

@section('content')
    <div class="md:flex md:-mx-6">
        <div class="md:px-6 md:w-2/3">
            <div class="leading-loose rounded shadow-lg">
                <h1 class="bg-gray-200 font-bold rounded-t px-4 py-6">
                    Магазинът Ви е готов! А сега накъде?
                </h1>
                <div class="bg-white rounded-b p-4">
                    <div class="text-gray-600">
                        Подготвили сме няколко бързи и лесни стъпки, които може да следвате, за да покажете на хората в интернет, че Вашият магазин е “отворил врати” и имате готовност да изпълнявате поръчки.
                    </div>
        
                    <x:admin.list-item class="mt-6">
                        <x:slot name="title">
                            1. Споделяне в социалните мрежи
                        </x:slot>
        
                        <x:slot name="description">
                            Споделете линк, водещ към Вашия сайт във всички социални мрежи (например на стената Ви във facebook), за да разберат приятелите Ви, че вече имате онлайн магазин. Това ще помогне изключително много да привлечете своите първи клиенти и същевременно не е нужно влагането на никакви ресурси.
                        </x:slot>
                    </x:admin.list-item>
        
                    <x:admin.list-item class="mt-6">
                        <x:slot name="title">
                            2. Изпращане и на лично съобщение
                        </x:slot>
        
                        <x:slot name="description">
                            Тъй като Вашата публикация може да не достигне до всичките Ви приятели, може да им пишете на лично съобщение да разгледат Вашия онлайн магазин.
                        </x:slot>
                    </x:admin.list-item>
        
                    <x:admin.list-item class="mt-6">
                        <x:slot name="title">
                            3. Приятел в нужда се познава
                        </x:slot>
        
                        <x:slot name="description">
                            Помолете близките Ви приятели да споделят Вашия онлайн магазин. Всички знаем, че рекламата “от уста на уста” е най-добрата реклама. На практика може да помолите приятелите си да споделят Вашия уебсайт, за да достигне новината и до техните приятели.
                        </x:slot>
                    </x:admin.list-item>
        
                    <x:admin.list-item class="mt-6">
                        <x:slot name="title">
                            4. Споделяне на продукти в подходящи групи
                        </x:slot>
        
                        <x:slot name="description">
                            За да разширите кръга от хора, до които да достигне новината, че вече имате собствен онлайн магазин, Ви препоръчваме да споделите продукти от сайта Ви в групи във Facebook тип: Купува - Продава.
                        </x:slot>
                    </x:admin.list-item>
        
                    <x:admin.list-item class="mt-6">
                        <x:slot name="title">
                            5. Facebook страница и Instagram профил
                        </x:slot>
        
                        <x:slot name="description">
                            Създавайки свои Facebook страница и Instagram профил, може да достигнете до още повече хора. Тези страници могат да бъдат следени от хора, които имат интерес към Вашите продукти, но не са в списъка Ви с приятели.
                        </x:slot>
                    </x:admin.list-item>
        
                    <x:admin.list-item class="mt-6">
                        <x:slot name="title">
                            6. Поддържане на активност в социалните мрежи
                        </x:slot>
        
                        <x:slot name="description">
                            Необходимо е да споделяте постове във Вашите социални мрежи, за да може по този начин да развивате своите страница, профил и т.н. Това отново се прави с цел достигане до повече потенциални купувачи на предлаганите от Вас продукти. Би било добре да пускате пост веднъж на няколко дена.
                        </x:slot>
                    </x:admin.list-item>
        
                    <x:admin.list-item class="mt-6">
                        <x:slot name="title">
                            7. Платформи за обяви като OLX, Bazar и други
                        </x:slot>
        
                        <x:slot name="description">
                            Да, Вие вече разполагате със собствен онлайн магазин, но може да използвате и други платформи, които Ви позволяват да излагате Вашите продукти на едно място заедно с много други продавачи. Винаги е от полза да “стъпите” на повече пазари или иначе казано, да използвате всички възможни инструменти за достигане до повече потенциални купувачи.
                        </x:slot>
                    </x:admin.list-item>
        
                    <x:admin.list-item class="mt-6">
                        <x:slot name="title">
                            8. Отношение към клиента
                        </x:slot>
        
                        <x:slot name="description">
                            При първите поръчки от сайта, може да изпращате и малки подаръчета. Идеята тук е да покажете персонално отношение към първите купувачи от Вашия онлайн магазин.
                        </x:slot>
                    </x:admin.list-item>
        
                    <x:admin.list-item class="mt-6">
                        <x:slot name="title">
                            9. Блогъри, влогъри и инфлуенсъри като цяло
                        </x:slot>
        
                        <x:slot name="description">
                            Тази стъпка изисква повече усилия от Ваша страна, но този тип реклама е максимално достоверен и шансът хората, които следят въпросния автор на блог статията или на видеото, да се доверят на неговата преценка е изключително голям.
                        </x:slot>
                    </x:admin.list-item>
        
                    <x:admin.list-item class="mt-6">
                        <x:slot name="title">
                            10. Разпечатване на флаери и постери за Вашия уебсайт
                        </x:slot>
        
                        <x:slot name="description">
                            Поставете ги във физическия Ви магазин, ако имате такъв. Така хората, които посещават обекта Ви ще научат, че вече разполагате и с онлайн магазин. Следователно може лесно и удобно да разгледат предлаганите от Вас продукти и онлайн.
                        </x:slot>
                    </x:admin.list-item>
                </div>
            </div>
        </div>

        <div class="md:px-6 md:w-1/3">
            <div class="mt-16 md:mt-0 leading-loose rounded shadow-lg">
                <h1 class="bg-gray-200 font-bold rounded-t px-4 py-6">
                    Често Задавани Въпроси
                </h1>
                <div class="bg-white rounded-b p-4">
                    <x:admin.list-item>
                        <x:slot name="title">
                            Без .fifi.bg накрая?
                        </x:slot>
        
                        <x:slot name="description">
                            Може ли сайта да не завършва на .fifi.bg? Да. За целта трябва обаче да: притежавате собствен домейн; да можете да създадете "А" запис в DNS настройките; да се свържите с нас, за да настроим някои неща. Ако нямате домейн, може да си закупите от <a href="https://www.icn.bg/bg/domains/" target="_blank">ICN</a>, <a href="https://www.superhosting.bg/web-hosting-register-domains.php#promotions" target="_blank">SuperHosting</a>, <a href="https://www.register.bg/" target="_blank">Register.bg</a>, както и много други. Услугата за настройване към Фифи е безплатна.
                        </x:slot>
                    </x:admin.list-item>
        
                    <x:admin.list-item class="mt-6">
                        <x:slot name="title">
                            Смяна на дизайна?
                        </x:slot>
        
                        <x:slot name="description">
                            Възможно ли е да правя промени по дизайна? Краткият отговор е "към момента не", поне "не" през админ панела. За да е максимално бързо и лесно създаването на сайт, Фифи не предлага много опции за модификация. Точно поради тази причина сме отворили кода - всеки програмист може да го вземе и да си го хоства на негова инфрастуктура. Тогава възможностите както за дизайн, така и за всичко останало, стават неограничени, но пък техническите изисквания скачат от нулеви до огромни.
                        </x:slot>
                    </x:admin.list-item>
                </div>
            </div>

            <div class="mt-16 leading-loose rounded shadow-lg">
                <h1 class="bg-gray-200 font-bold rounded-t px-4 py-6">
                    Контакт с Фифи
                </h1>
                <div class="bg-white rounded-b p-4">
                    <div class="text-gray-600">
                        При въпроси и коментари, може да пишете на екипа на Фифи директно през формата отдолу.
                    </div>                    

                    <livewire:admin.contact />
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/settings.blade.php
@extends('layouts.admin', ['title' => 'Настройки'])

@section('content')
    <livewire:admin.save-settings />
@endsection

resources/views/admin/texts.blade.php
@extends('layouts.admin', ['title' => 'Текстове'])

@section('content')
    <livewire:admin.save-texts />
@endsection